### ISSUE TITLE
+ references section in quarto 

### ISSUE THREAD

**Issue by 7yl4r** [tbep-tech/shiny-workshop#5]
Two questions about referencing came up when in the middle of the quarto section.
In a future iteration of the workshop it may be useful to walk through using bibtex (or other) reference systems with the similar `@` notation with tables + figures at this time.

**Comment by fawda123** [comment]
@7yl4r I agree, there's already some content in the supplement: https://tbep-tech.github.io/shiny-workshop/addlquarto.html#citations-and-references I didn't want to include this in the workshop since it wasn't directly about dashboards, but it's definitely a great advantage of Quarto.
